spring:
  profiles:
    active: dev
  application:
    name: team5_config_server



server:
  tomcat:
    keep-alive-timeout: 65000
    connection-timeout: 20000
    max-keep-alive-requests: 10000
  port: 8888

eureka:
  client:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
